### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by mirabelenkiy-circle** [AztecProtocol/ignition-verification#17]
Both yarn run validate and npm run validate give a compile error:

```
npm run validate

> ignition-points@1.0.0 validate
> node index.js validate

/Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:20607
    crypto.getRandomValues = crypto.randomFillSync;
                           ^

TypeError: Cannot set property getRandomValues of #<Object> which has only a getter
    at /Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:20607:28
    at ./src/mcl/mcl.js (/Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:20615:3)
    at __webpack_require__ (/Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:30:30)
    at ./src/decodePoint.js (/Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:20262:11)
    at __webpack_require__ (/Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:30:30)
    at ./src/index.js (/Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:20338:19)
    at __webpack_require__ (/Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:30:30)
    at 0 (/Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:24589:18)
    at __webpack_require__ (/Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:30:30)
    at /Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:94:18

Node.js v18.16.0
```

**Comment by critesjosh** [comment]
Can you try with node v10? This code is quite old 😅

**Comment by mirabelenkiy-circle** [comment]
@critesjosh I updated to 10.2.4 and got the same problem.

```
default-admin ignition-verification % npm -v
10.2.4
default-adminignition-verification % node ./scripts/parseTranscripts.js
/Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:20607
    crypto.getRandomValues = crypto.randomFillSync;
                           ^

TypeError: Cannot set property getRandomValues of #<Object> which has only a getter
    at /Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:20607:28
    at ./src/mcl/mcl.js (/Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:20615:3)
    at __webpack_require__ (/Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:30:30)
    at ./src/decodePoint.js (/Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:20262:11)
    at __webpack_require__ (/Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:30:30)
    at ./src/index.js (/Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:20338:19)
    at __webpack_require__ (/Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:30:30)
    at 0 (/Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:24589:18)
    at __webpack_require__ (/Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:30:30)
    at /Users/default-admin/Documents/Dev/ignition-verification/node_modules/@aztec/bn128/dist/bundle.node.js:94:18

Node.js v21.6.2
```

**Comment by critesjosh** [comment]
seems to be working for me with v10.24.1

![image](https://github.com/AztecProtocol/ignition-verification/assets/18372439/01959753-80bb-436d-aa86-1c8eee05c499)
