### ISSUE TITLE
Python version incoherency

### ISSUE THREAD

**Issue by l-henri** [AztecProtocol/ignition-verification#3]
Hello,

On the repo it is stated that python 3 is required.
However, in order to run 
> npm install
correctly, one needs python 2.X.
Which version should be used?
Thanks,

**Comment by ArnSch** [comment]
Hey @l-henri, can you share a trace of the error you're getting when running `npm install`?

I know of some issues related to `node-gyp`, which used to not play nice with python 3, but as far as I can tell those were addressed.

**Comment by l-henri** [comment]
Here it is:
`npm install

> secp256k1@3.8.0 install C:\path\ignition-verification\node_modules\secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.8.0 rebuild C:\path\ignition-verification\node_modules\secp256k1
> node-gyp rebuild


C:\path\ignition-verification\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\hlieutaud\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\path\ignition-verification\node_modules\secp256k1
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.8.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.8.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hlieutaud\AppData\Roaming\npm-cache\_logs\2020-01-13T12_32_00_324Z-debug.log
"Secp256k1 bindings compilation fail. Pure JS implementation will be used."
npm WARN ignition-points@1.0.0 No repository field.
`

**Comment by ArnSch** [comment]
What version(s) of python do you have installed at the moment?

**Comment by ArnSch** [comment]
@l-henri, could you try updating your npm, and updating node-gyp? going off of [this issue](https://github.com/nodejs/node-gyp/issues/1977), which seems to match the above.

**Comment by ArnSch** [comment]
It might be a sub-dependency issue, will double check.

**Comment by l-henri** [comment]
Hello, 
I am changing my machine this afternoon so I will make a clean NPM install and I will report.
Right now my version is 6.9.0.

**Comment by ArnSch** [comment]
Sorry for the slow reply. I don't have a windows machine available so debugging is taking time. I pushed a small fix today, but don't think it'll directly address the specific trouble you're having.

**Comment by s4m0r4m4** [comment]
Just passing along what I found when I was hitting a similar issue. I had the same issue on npm 6.9.0, which depended on node-gyp 3.8.0, which only supports python 2. In your stack trace you can also see that you're using node-gyp 3.8.0, that syntax error is because its trying to run a python 2 line of code in python 3.

I updated to npm 6.14.4, which uses node-gyp 5+, which can support python 3. Then the npm install worked fine. Hope that helps!
